name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set version variable
        run: |
          echo "SUPERSET_REPO=apache/superset" >> $GITHUB_ENV
          echo "SUPERSET_VERSION=4.1.1" >> $GITHUB_ENV
          echo "DSFR_VERSION=1.13.0" >> $GITHUB_ENV
          echo "DSFR_CHART_VERSION=1.0.0" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -f Dockerfile --build-arg TAG_DSFR=${{ env.DSFR_VERSION }} --build-arg TAG_DSFR_CHART=${{ env.DSFR_CHART_VERSION }} --build-arg SUPERSET_VERSION=${{ env.SUPERSET_VERSION }} -t $IMAGE_NAME:${{ env.SUPERSET_VERSION }}-${{ env.DSFR_VERSION }} .

      - name: Push Docker image
        run: docker push $IMAGE_NAME:${{ env.SUPERSET_VERSION }}-${{ env.DSFR_VERSION }}
