name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - img-chartsgouv

env:
  SUPERSET_VERSION: ${{ vars.DSFR_VERSION }} 
  DSFR_VERSION: ${{ vars.DSFR_VERSION }} 
  DSFR_CHART_VERSION: ${{ vars.DSFR_VERSION }} 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set version variable
        run: |
          # Determine if we are on pre-release and append '-test' to the tag
          if [[ "${GITHUB_REF}" == "refs/heads/pre-release" ]]; then
            echo "IMAGE_NAME=ghcr.io/${{ github.repository }}-test" >> $GITHUB_ENV
          else
            echo "IMAGE_NAME=ghcr.io/${{ github.repository }}" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        run: docker build -f Dockerfile 
          --build-arg TAG_DSFR=$DSFR_VERSION 
          --build-arg TAG_DSFR_CHART=$DSFR_CHART_VERSION 
          --build-arg SUPERSET_VERSION=$SUPERSET_VERSION 
          -t $IMAGE_NAME:$SUPERSET_VERSION-$DSFR_VERSION-$DSFR_CHART_VERSION .

      - name: Push Docker image
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/pre-release'
        run: docker push $IMAGE_NAME:$SUPERSET_VERSION-$DSFR_VERSION-$DSFR_CHART_VERSION
