name: Lint Helm

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'docs/installation/helm/**'
  pull_request:
    branches: [main]
    paths:
      - 'docs/installation/helm/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      TMP_DIR: /tmp/superset-chart
    steps:
      - uses: actions/checkout@v7

      - uses: azure/setup-helm@v5
        with:
          version: latest

      - run: helm repo add superset https://apache.github.io/superset/
      - run: helm repo update

      - name: Pull chart and lint
        run: |
          rm -rf "$TMP_DIR"
          mkdir -p "$TMP_DIR"
          helm pull superset/superset --untar --untardir "$TMP_DIR"
          helm lint "$TMP_DIR"/superset -f docs/installation/helm/values.yaml

          rm -rf "$TMP_DIR"

      - run: helm template test-release "$TMP_DIR"/superset -f docs/installation/helm/values.yaml > /dev/null
